backend/backend/urls.py
from django.urls import include, path
from django.contrib import admin
from user import views
from farm import views as farm_views
from field import views as field_views
from task import views as task_views
from sensor import views as sensor_views
from django.conf.urls.static import static
from backend import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signup),
    path('signin/', views.signin), 
    path('getuserbyemail/<str:email>/', views.get_user),
    path('getuserbyid/<int:id>/', views.getUserById),
    path('createfarm/', farm_views.create_farm),
    path('getfarmbyownerorfarmer/<int:id>/', farm_views.getFarmByOwnerOrFarmer),
    path('getfieldsbyid/<int:id>/', field_views.getFieldsById),
    path('createfield/', field_views.create_field),
    path('addfarmer/<int:id>/', farm_views.addFarmer),
    path('addfieldmanager/<int:id>/', field_views.add_field_manager),
    path('getfarmbyfieldmanager/<int:id>/', farm_views.getFarmByFieldManager),
    path('getfieldsbymanager/<int:id>/', field_views.getFieldsByManager),
    path('getteam/<int:id>/', views.getTeam),
    path('createtask/', task_views.create_task),
    path('getfieldbyid/<int:id>/', field_views.getFieldById),
    path('gettasksbyfarm/<int:id>/', task_views.get_tasks_by_farm),
    path('deleteuser/<str:email>/', views.deleteUser),
    path('deleteaccount/', views.deleteAccount),
    path('changepassword/', views.changePassword),
    path('deletefield/<int:id>/', field_views.deleteField),
    path('gettasksbyassignee/<int:id>/', task_views.get_tasks_by_assignee),
    path('edituser/<int:id>/', views.editUser),  
    path('getsensors/<int:id>/', sensor_views.getSensors),
    path('createsensor/', sensor_views.create_sensor),
    path('deletesensor/<int:id>/', sensor_views.delete_sensor),
    path('scan/', include(('parseImage.urls', 'parseImage'), namespace="parseImage")),
    path('deletetask/<int:id>/', task_views.delete_task),
    path('updatetaskstatus/<int:id>/', task_views.update_task_status),
    path('newscan/', include(('predict.urls', 'predict'), namespace="predict")),
    ]

backend/predict/urls.py
from django.urls import path

from backend import settings
from . import views
urlpatterns = [
    #path('', views.yolov5_view, name='post')
    path('results/', views.yolov5_view, name='results')
]

backend/predict/models.py
# Create your models here.
import os

from django.db import models
from django.utils.translation import gettext_lazy as _


class ImageModel(models.Model):
    image = models.ImageField(_("image"), upload_to='images')

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"

    def __str__(self):
        return str(os.path.split(self.image.path)[-1])

backend/predict/forms.py
from django import forms
from .models import ImageModel


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImageModel
        fields = ['image']

backend/predict/views.py
'''from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
import numpy as np
import argparse
import time
import cv2
import os
import torch
from PIL import Image
import numpy as np
#from yolov5.models.experimental import attempt_load
#from yolov5.utils.plots import plot_one_box
from matplotlib import pyplot as plt
#from yolov5.utils.general import non_max_suppression
#from yolov5.utils.torch_utils import select_device
#from yolov5.utils.autoanchor import check_anchors
# Create your views here.
from django.http import HttpResponse

from django.conf import settings


def index(request):
    return render(request, 'parseImage/index.html')
model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt')
def process_images(input_img):
    # Get the selected image file paths
    classIDs = []
    # fruitlist = []
    fruitsfound = {}
    # Process each selected image
    for file_path in input_img:
        # Load the image
        image = cv2.imread(file_path)
        if image.size == 0:
            print("no img")
        # Process the image with your model
        # ... (your model inference code here)
        results = model(image)
        # Display the image with the results
        # ... (your code to display the image here)
        results.print()
        results.show()
    cv2.imwrite(
        os.path.join(settings.BASE_DIR, f'static/parseImage/{img}_mod.jpg'),
        image,)
    return fruitsfound, f'{image}_mod.jpg'
# Images
#imgs = ['D:/OD/Supra/images/train/22.jpg','D:/OD/Supra/images/train/34.jpg']  # batch of images
def results(request):
    
    if request.method == 'POST' and request.FILES['fileup']:
        myfile = request.FILES['fileup']
        fs = FileSystemStorage()
        # conf = float(request.POST['confidence']) * 0.1
        conf = 0
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        fruitOut, outImg = process_images(filename)
        # return HttpResponse("uploaded at %s.. the list of fruits are: %s" % (uploaded_file_url, str(fruitOut)))
        return render(request, 'parseImage/results.html', {
            'outImg': outImg,
            'fruitOut': fruitOut
        })
    # return render(request, 'parseImage/results.html')
    return HttpResponse("could not upload")

'''
'''
import io
from PIL import Image as im
import torch

from django.shortcuts import render
from django.views.generic.edit import CreateView

from .models import ImageModel
from .forms import ImageUploadForm

def index(request):
    return render(request, 'image/imagemodel_form.html')
class UploadImage(CreateView):
    model = ImageModel
    template_name = 'image/imagemodel_form.html'
    fields = ["image"]

    def post(self, request, *args, **kwargs):
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            img = request.FILES.get('image')
            img_instance = ImageModel(
                image=img
            )
            img_instance.save()

            uploaded_img_qs = ImageModel.objects.filter().last()
            img_bytes = uploaded_img_qs.image.read()
            img = im.open(io.BytesIO(img_bytes))

            # Change this to the correct path
            model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt')
            results = model(img, size=640)
            results.render()
            for img in results.imgs:
                img_base64 = im.fromarray(img)
                img_base64.save("media/yolo_out/image0.jpg", format="JPEG")

            inference_img = "/media/yolo_out/image0.jpg"

            form = ImageUploadForm()
            context = {
                "form": form,
                "inference_img": inference_img
            }
            return render(request, 'image/imagemodel_form.html', context)

        else:
            form = ImageUploadForm()
        context = {
            "form": form
        }
        return render(request, 'image/imagemodel_form.html', context)
    '''
'''
import torch
import numpy as np
from django.shortcuts import render
import torchvision.transforms as transforms
# Define your YOLOv5 model and related functions here
from PIL import Image
from io import BytesIO

def yolov5_view(request):
    if request.method == 'POST':
        uploaded_file = request.FILES.getList['image']
                # Read the file data
        file_data = uploaded_file.read()
        
        # Create a BytesIO object from the file data
        file_stream = BytesIO(file_data)
        img=Image.open(file_stream)
        image_np = np.array(img)
        image_tensor = torch.from_numpy(image_np).unsqueeze(0)
        # Open the image using PIL
        
        #Image.open(file_stream)
        # Load YOLOv5 model
        model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt') # Replace with your code to load the model
        
        # Define the preprocessing transformations
        preprocess = transforms.Compose([
            transforms.Resize((640, 480)),  # Resize to desired dimensions
            transforms.ToTensor(),  # Convert to tensor
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # Normalize
])

# Apply the preprocessing transformations
        preprocessed_image = preprocess(img)

        # Run the model on the preprocessed image
        predictions = model(preprocessed_image)  # Replace with your code to make predictions
        # Process the predictions as needed
        #processed_predictions = process_predictions(predictions)  # Replace with your code to process the predictions
        
        # Return the results as a response
        return render(request, 'results.html', {'predictions': predictions})
    
    # If it's not a POST request, render the form template
    return render(request, 'upload.html')
'''
from django.shortcuts import render
from PIL import Image
import torch
from io import BytesIO
from collections import Counter
import os
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.conf import settings

def yolov5_view(request):
    print("SYUDHAUYADHSY")
    class_counts_total = 0
    if request.method != 'POST':
        # If it's not a POST request, render the form template
        return render(request, 'upload.html')
    # Assuming you have a form with an 'image' field for file upload
    uploaded_files = request.FILES.getlist('fileup')
    fs = FileSystemStorage()
    # Load the YOLOv5 model
    model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt')
    # Create the output directory if it doesn't exist    
    output_dir = 'output'
    output_dir = os.path.join(settings.MEDIA_ROOT, 'output')
    os.makedirs(output_dir, exist_ok=True)
    # List to store the predictions for each image
    predictions_list = []
    image_paths = []
    a = 0   

    # Process each uploaded image
    for uploaded_file in uploaded_files:
        # Read the file data
        file_data = uploaded_file.read()

# Create a BytesIO object from the file data
        file_stream = BytesIO(file_data)

# Open the image using PIL
        image = Image.open(file_stream)

        # Run the model on the image
        results = model(image)
        #results.print()
        #results.show()
        #results.save()

        results_count=results.pandas().xyxy[0]
        # Add the predictions to the list
        #predictions_list.append((results_count,image_paths))
        predictions_list.append(results_count)
        # Save the image in the output directory
        #image_filename = os.path.join(output_dir, results.save())
        #image.save(image_filename)
        #filename = fs.save(output_dir, results)
        total_classes = sum(len(predictions) for predictions in predictions_list)
        # Count the occurrences of each class
        #class_names = [prediction[0] for predictions in predictions_list for prediction in predictions]
            # Count the occurrences of each class
        #class_counts = Counter(class_names)
        #print(class_counts)
        #results_blue=print(results_count['name'].value_counts()['Blue'])
        # Calculate the occurrences of each class
        class_counts=results_count['name'].value_counts()

        print("boas")
        
        print(class_counts[0])
      

        class_counts_total = class_counts.add(class_counts_total, fill_value=0)
        
       



        
        print(class_counts_total)
        # Get the count of "Blue" class across all images
        #blue_count1 = sum(class_counts.get("Blue", 0) for class_name, count in class_counts.items())
        #blue_count = class_counts.get("Blue", 0) 
        #blue_count = sum(class_counts.get('Blue', 0) for class_counts in predictions_list)
        blue_count = sum(count for class_name, count in class_counts.items() if class_name == 'Blue')
        # Save the images


        for i,image_array in enumerate(results.render()):

            print(i)
        # Convert the NumPy array to a PIL image
            image_pil = Image.fromarray(image_array)
        
            # Save the image
            
            image_filename = f"image_{a}.jpg"
            print(image_filename)
            image_path = os.path.join(output_dir, image_filename)
            image_pil.save(image_path)
            
            a+=1
            
        
        image_paths.append(image_path)

        print(image_paths)
                    # Save the image in the output directory
        
        
 
        #print(results_blue)
        #results_red=print(results_count['name'].value_counts()['Red'])

backend/predict/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block page_meta %}
  {% endblock %}

  {% block vendor_css %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/vendor/bootstrap.min.css' %}" />
    <link href="{% static 'css/ekko-lightbox.css' %}" rel="stylesheet">
  {% endblock vendor_css %}

  {% block site_css %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/styles/style.css' %}" />
  {% endblock %}

  {# Page-specific styles #}
  {% block on_page_css %}{% endblock %}

  {% block extra_head %}
    {# Extra header stuff (scripts, styles, metadata, etc) #}
  {% endblock %}

  <title>My Website - {% block title %}{% endblock %}</title>
</head>
<body class="{% block body_class %}{% endblock %}">
  {% include 'partials/_nav.html' %}

  {{ form.image.errors }}
<div class="fluid-container mx-2">
    
  {% block header %}
    {% include 'partials/_header.html' %}
  {% endblock header %}


  {% if messages %}
      {% for message in messages %}
        <div class="message">
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" id="djangoMessage" role="alert">
            {{ message }}
            <button type="button" class="close" aria-label="Close" data-dismiss="alert">
              <span aria-hidden="true" id="messageDialogCloseBtn">&times;</span></button>       
          </div>
        </div>    
      {% endfor %}
    {% endif %}

  <div class="row">
    {% block leftbar %}
        {# Leftbar on the Page #}
    {% endblock %}
    {% block content %}
        {# Page content will go here #}
    {% endblock %}
  </div>
</div>  

{# Modal HTML #}
{% block modals %}
{% endblock %}

{# Vendor javascript #}
{% block vendor_js %}
{% endblock %}

{# Global javascript #}
{% block site_js %}
  {% include 'partials/_scripts.html' %}
{% endblock %}

{# Shared data for javascript #}
{% block shared_data %}
{% endblock %}

{# On Page javascript #}
{% block on_page_js %}
{% endblock %}

</body>
</html>

backend/predict/templates/index copy.html
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
  
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">

	
	
    <style>
	/*just bg and body style*/
.container{
background-color:#1E2832;
padding-bottom:20px;
margin-top:10px;
border-radius:5px;
}
.center{
text-align:center;  
}
#top{
margin-top:20px;  
}
.btn-container{
background:#fff;
border-radius:5px;
padding-bottom:20px;
margin-bottom:20px;
}
.white{
color:white;
}
.imgupload{
color:#1E2832;
padding-top:40px;
font-size:7em;
}
#namefile{
color:black;
}
h4>strong{
color:#ff3f3f
}
.btn-primary{
border-color: #ff3f3f !important;
color: #ffffff;
text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
background-color: #ff3f3f !important;
border-color: #ff3f3f !important;
}

/*these two are set to not display at start*/
.imgupload.ok{
display:none;
color:green;
}
.imgupload.stop{
display:none;
color:red;
}


/*this sets the actual file input to overlay our button*/ 
#fileup{
opacity: 0;
-moz-opacity: 0;
filter: progid:DXImageTransform.Microsoft.Alpha(opacity=0);
width:200px;
cursor: pointer;
position:absolute;
left: 50%;
transform: translateX(-50%);
bottom: 40px;
height: 50px;
}

/*switch between input and not active input*/
#submitbtn{
  padding:5px 50px;
  display:none;
}
#fakebtn{
  padding:5px 40px;
}


/*www.emilianocostanzo.com*/
#sign{
	color:#1E2832;
	position:fixed;
	right:10px;
	bottom:10px;
	text-shadow:0px 0px 0px #1E2832;
	transition:all.3s;
}
#sign:hover{
	color:#1E2832;
	text-shadow:0px 0px 5px #1E2832;
}
	
.slidecontainer {
  width: 100%;
}

.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 25px;
  background: #d3d3d3;
  outline: none;
  opacity: 0.7;
  -webkit-transition: .2s;
  transition: opacity .2s;
}

.slider:hover {
  opacity: 1;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 25px;
  height: 25px;
  background: #4CAF50;
  cursor: pointer;
}

.slider::-moz-range-thumb {
  width: 25px;
  height: 25px;
  background: #4CAF50;
  cursor: pointer;
}
</style>
</head>
<body>
<!--form method="post" action="{% url 'parseImage:results' %}" enctype="multipart/form-data">
    {% csrf_token %}
	<label for="image">Image</label>
    <input type="file" name="myfile" id="image">
	<label for="image">Confidence</label>
	<input type="range" min="0" max="10" value="5" class="slider" id="conf" name="confidence">
    <button type="submit">Scan for Fruits</button>
  </form-->

<div class="container center">
	<div class="row">
		<div class="col-md-12">
			<h1 class="white">Lets start scanning fruits !!</h1>
			
		</div>
	</div>
	
	<form name="upload" method="post" action="{% url 'parseImage:results' %}" enctype="multipart/form-data" accept-charset="utf-8">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-6 col-md-offset-3 center">
				<div class="btn-container">
					<!--the three icons: default, ok file (img), error file (not an img)-->
					<h1 class="imgupload"><i class="fa fa-file-image-o"></i></h1>
					<h1 class="imgupload ok"><i class="fa fa-check"></i></h1>
					<h1 class="imgupload stop"><i class="fa fa-times"></i></h1>
					<!--this field changes dinamically displaying the filename we are trying to upload-->
					<p id="namefile">Only pics allowed! (jpg,jpeg,bmp,png)</p>
					<!--our custom btn which which stays under the actual one-->
					<button type="button" id="btnup" class="btn btn-primary btn-lg">Browse for your pic!</button>
					<!--this is the actual file input, is set with opacity=0 beacause we wanna see our custom one-->
					<input type="file" value="" name="fileup" id="fileup">
				</div>
			</div>
		</div>
			<!--additional fields-->
		<div class="row">			
			<div class="col-md-12">
				<!--the defauld disabled btn and the actual one shown only if the three fields are valid-->
				<input type="submit" value="Submit!" class="btn btn-primary" id="submitbtn">
				<button type="button" class="btn btn-default" disabled="disabled" id="fakebtn">Submit! <i class="fa fa-minus-circle"></i></button>
			</div>
		</div>
	</form>
</div>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
      
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<script type="text/javascript">
	
	$('#fileup').change(function(){
//here we take the file extension and set an array of valid extensions
	console.log("in fucntion");
    var res=$('#fileup').val();
    var arr = res.split("\\");
    var filename=arr.slice(-1)[0];
    filextension=filename.split(".");
    filext="."+filextension.slice(-1)[0];
    valid=[".jpg",".png",".jpeg",".bmp"];
//if file is not valid we show the error icon, the red alert, and hide the submit button
    if (valid.indexOf(filext.toLowerCase())==-1){
        $( ".imgupload" ).hide("slow");
        $( ".imgupload.ok" ).hide("slow");
        $( ".imgupload.stop" ).show("slow");
      
        $('#namefile').css({"color":"red","font-weight":700});
        $('#namefile').html("File "+filename+" is not  pic!");
        
        $( "#submitbtn" ).hide();
        $( "#fakebtn" ).show();
    }else{
        //if file is valid we show the green alert and show the valid submit
        $( ".imgupload" ).hide("slow");
        $( ".imgupload.stop" ).hide("slow");
        $( ".imgupload.ok" ).show("slow");
		console.log("image ok");
        $('#namefile').css({"color":"green","font-weight":700});
        $('#namefile').html(filename);
      
        $( "#submitbtn" ).show();
        $( "#fakebtn" ).hide();
    }
});

</script>

</body>

backend/predict/templates/index.html

<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
  
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">

	
	
    <style>
	/*just bg and body style*/
.container{
background-color:#1E2832;
padding-bottom:20px;
margin-top:10px;
border-radius:5px;
}
.center{
text-align:center;  
}
#top{
margin-top:20px;  
}
.btn-container{
background:#fff;
border-radius:5px;
padding-bottom:20px;
margin-bottom:20px;
}
.white{
color:white;
}
.imgupload{
color:#1E2832;
padding-top:40px;
font-size:7em;
}
#namefile{
color:black;
}
h4>strong{
color:#ff3f3f
}
.btn-primary{
border-color: #ff3f3f !important;
color: #ffffff;
text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
background-color: #ff3f3f !important;
border-color: #ff3f3f !important;
}

/*these two are set to not display at start*/
.imgupload.ok{
display:none;
color:green;
}
.imgupload.stop{
display:none;
color:red;
}


/*this sets the actual file input to overlay our button*/ 
#fileup{
opacity: 0;
-moz-opacity: 0;
filter: progid:DXImageTransform.Microsoft.Alpha(opacity=0);
width:200px;
cursor: pointer;
position:absolute;
left: 50%;
transform: translateX(-50%);
bottom: 40px;
height: 50px;
}

/*switch between input and not active input*/
#submitbtn{
  padding:5px 50px;
  display:none;
}
#fakebtn{
  padding:5px 40px;
}


/*www.emilianocostanzo.com*/
#sign{
	color:#1E2832;
	position:fixed;
	right:10px;
	bottom:10px;
	text-shadow:0px 0px 0px #1E2832;
	transition:all.3s;
}
#sign:hover{
	color:#1E2832;
	text-shadow:0px 0px 5px #1E2832;
}
	
.slidecontainer {
  width: 100%;
}

.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 25px;
  background: #d3d3d3;
  outline: none;
  opacity: 0.7;
  -webkit-transition: .2s;
  transition: opacity .2s;
}

.slider:hover {
  opacity: 1;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 25px;
  height: 25px;
  background: #4CAF50;
  cursor: pointer;
}

.slider::-moz-range-thumb {
  width: 25px;
  height: 25px;
  background: #4CAF50;
  cursor: pointer;
}
</style>
</head>
<body>
<!--form method="post" action="{% url 'parseImage:results' %}" enctype="multipart/form-data">
    {% csrf_token %}
	<label for="image">Image</label>
    <input type="file" name="myfile" id="image">
	<label for="image">Confidence</label>
	<input type="range" min="0" max="10" value="5" class="slider" id="conf" name="confidence">
    <button type="submit">Scan for Fruits</button>
  </form-->

<div class="container center">
	<div class="row">
		<div class="col-md-12">
			<h1 class="white">Lets start scanning fruits !!</h1>
			
		</div>
	</div>
	
	<form name="upload" method="post" action="{% url 'parseImage:results' %}" enctype="multipart/form-data" accept-charset="utf-8">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-6 col-md-offset-3 center">
				<div class="btn-container">
					<!--the three icons: default, ok file (img), error file (not an img)-->
					<h1 class="imgupload"><i class="fa fa-file-image-o"></i></h1>
					<h1 class="imgupload ok"><i class="fa fa-check"></i></h1>
					<h1 class="imgupload stop"><i class="fa fa-times"></i></h1>
					<!--this field changes dinamically displaying the filename we are trying to upload-->
					<p id="namefile">Only pics allowed! (jpg,jpeg,bmp,png)</p>
					<!--our custom btn which which stays under the actual one-->
					<button type="button" id="btnup" class="btn btn-primary btn-lg">Browse for your pic!</button>
					<!--this is the actual file input, is set with opacity=0 beacause we wanna see our custom one-->
					<input type="file" value="" name="fileup" id="fileup">
				</div>
			</div>
		</div>
			<!--additional fields-->
		<div class="row">			
			<div class="col-md-12">
				<!--the defauld disabled btn and the actual one shown only if the three fields are valid-->
				<input type="submit" value="Submit!" class="btn btn-primary" id="submitbtn">
				<button type="button" class="btn btn-default" disabled="disabled" id="fakebtn">Submit! <i class="fa fa-minus-circle"></i></button>
			</div>
		</div>
	</form>
</div>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
      
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<script type="text/javascript">
	
	$('#fileup').change(function(){
//here we take the file extension and set an array of valid extensions
	console.log("in fucntion");
    var res=$('#fileup').val();
    var arr = res.split("\\");
    var filename=arr.slice(-1)[0];
    filextension=filename.split(".");
    filext="."+filextension.slice(-1)[0];
    valid=[".jpg",".png",".jpeg",".bmp"];
//if file is not valid we show the error icon, the red alert, and hide the submit button
    if (valid.indexOf(filext.toLowerCase())==-1){
        $( ".imgupload" ).hide("slow");
        $( ".imgupload.ok" ).hide("slow");
        $( ".imgupload.stop" ).show("slow");
      
        $('#namefile').css({"color":"red","font-weight":700});
        $('#namefile').html("File "+filename+" is not  pic!");
        
        $( "#submitbtn" ).hide();
        $( "#fakebtn" ).show();
    }else{
        //if file is valid we show the green alert and show the valid submit
        $( ".imgupload" ).hide("slow");
        $( ".imgupload.stop" ).hide("slow");
        $( ".imgupload.ok" ).show("slow");
		console.log("image ok");
        $('#namefile').css({"color":"green","font-weight":700});
        $('#namefile').html(filename);
      
        $( "#submitbtn" ).show();
        $( "#fakebtn" ).hide();
    }
});

</script>

</body>

backend/predict/templates/results.html
<!DOCTYPE html>
<html>
<head>
    <title>Results</title>
    <style>
        .output-image {
            max-width: 500px;
            max-height: 500px;
        }
    </style>
</head>
<body>
    <h1>YOLOv5 Model Results</h1>
    {% with total_images=predictions_list|length %}
    <h3>Total Images: {{ total_images }}</h3>
{% endwith %}

    <h3>Total Berries detected: {{ total_classes }}</h3>
    <h3>Total Blue Berries detected: {{ class_counts_total }}</h3>

</body>
</html>